server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddabong
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


  jwt:
    secret: testSecretKey20240316testSecretKey20240316testSecretKey20240316
    token:
      access-expiration-time: 3600000
      refresh-expiration-time: 86400000

  data:
    redis:
      host: localhost
      port: 6379
