server:
  port: 8080

spring:
  profiles:
    group:
      "local": "db, secret, s3, redis, security"
      "prod": "db, secret, s3, redis, security"
    default: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


